name: pull request
on: 
  pull_request:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused --timeout=3m

    - name: download opa
      run: |
        curl -L -o /usr/local/bin/opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod 755 /usr/local/bin/opa

    - name: download cfssl
      run: |
        curl -L -o /usr/local/bin/cfssl https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
        curl -L -o /usr/local/bin/cfssljson https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
        chmod 755 /usr/local/bin/cfssl /usr/local/bin/cfssljson

    - name: build and test
      run: |
        export GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}
        make certs
        make test
        make dockerimage

    - name: Push
      run: |
        export GIT_TAG_NAME=${GITHUB_HEAD_REF##*/}
        make dockerpush

    - name: Publish Codecoverage report
      run: bash <(curl -s https://codecov.io/bash)
